# Generated by Django 6.0.6 on 2026-06-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0002_links_alter_about_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
    ]
