# Generated by Django 6.0.6 on 2026-06-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
