# Generated by Django 6.0.6 on 2026-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_rename_update_at_category_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
